name: reflect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.8.4
  video_player: ^2.9.1
  flutter_svg: ^2.0.10+1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  firebase_core: ^4.1.0
  flutter_riverpod: ^2.5.1
  google_nav_bar: ^5.0.6
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_quill: ^11.4.2
  http: ^1.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  hive: ^2.2.3
  flutter_sliding_up_panel: ^2.1.1
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: "^0.14.1"
  encrypt: ^5.0.3
  conduit_password_hash: ^5.1.3
  unique_identifier: ^0.4.0
  device_info_plus: ^11.1.1
  flutter_secure_storage: ^9.2.2
  pointycastle: ^3.9.1
  mongo_dart: ^0.10.3
  image_picker: ^1.1.2
  icon_decoration: ^2.1.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  google_sign_in_web: ^1.0.0
  video_player_web: ^2.4.0
  video_player_win: ^3.2.0
  window_manager: ^0.5.1
  googleapis_auth: ^2.0.0
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/videos/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
