// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZOIQn0j9jNEiCo63xXNA-IDwCqPk-7c',
    appId: '1:176638636870:web:b2662537f41594d2c9eb47',
    messagingSenderId: '176638636870',
    projectId: 'reflect-47',
    authDomain: 'reflect-47.firebaseapp.com',
    storageBucket: 'reflect-47.firebasestorage.app',
    measurementId: 'G-3RKWWKRDDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuTFEKSGpu2_jNJ5GeBHeqYz3GSpuF6Q',
    appId: '1:176638636870:android:07e65dd1717c5f77c9eb47',
    messagingSenderId: '176638636870',
    projectId: 'reflect-47',
    storageBucket: 'reflect-47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cugTnHFUxbp_AvUVcV34x2qo_mL5-ko',
    appId: '1:491140441464:ios:cd517964a28db6cebf548d',
    messagingSenderId: '491140441464',
    projectId: 'reflect-0',
    storageBucket: 'reflect-0.firebasestorage.app',
    iosBundleId: 'com.example.reflect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6AefcEqWRcubMv6dxnCAgFfFROXqTyQ',
    appId: '1:176638636870:web:2b264858206102a0c9eb47',
    messagingSenderId: '176638636870',
    projectId: 'reflect-47',
    authDomain: 'reflect-47.firebaseapp.com',
    storageBucket: 'reflect-47.firebasestorage.app',
    measurementId: 'G-9MCF865JDJ',
  );

}