// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWC2u4Deo7mevtFBgkXRwwzGsX5dWuZU',
    appId: '1:491140441464:web:b638854b4051e086bf548d',
    messagingSenderId: '491140441464',
    projectId: 'reflect-0',
    authDomain: 'reflect-0.firebaseapp.com',
    storageBucket: 'reflect-0.appspot.com',
    databaseURL: ''
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzsdDar0lpf5OkZ1GdVdAwdruC0OuqT0',
    appId: '1:491140441464:android:c991d8719dc4a23ebf548d',
    messagingSenderId: '491140441464',
    projectId: 'reflect-0',
    storageBucket: 'reflect-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3cugTnHFUxbp_AvUVcV34x2qo_mL5-ko',
    appId: '1:491140441464:ios:cd517964a28db6cebf548d',
    messagingSenderId: '491140441464',
    projectId: 'reflect-0',
    storageBucket: 'reflect-0.appspot.com',
    iosBundleId: 'com.example.reflect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWC2u4Deo7mevtFBgkXRwwzGsX5dWuZU',
    appId: '1:491140441464:web:a390b698d573e79bbf548d',
    messagingSenderId: '491140441464',
    projectId: 'reflect-0',
    authDomain: 'reflect-0.firebaseapp.com',
    storageBucket: 'reflect-0.appspot.com',
  );
}
